# wengwengweng

[[columns]]
kind = "Pid"
style = "BrightYellow"
numeric_search = true
nonnumeric_search = false
align = "Left"

[[columns]]
kind = "Separator"
style = "White"
numeric_search = false
nonnumeric_search = false
align = "Left"

[[columns]]
kind = "UsageCpu"
style = "ByPercentage"
numeric_search = false
nonnumeric_search = false
align = "Right"

[[columns]]
kind = "UsageMem"
style = "ByPercentage"
numeric_search = false
nonnumeric_search = false
align = "Right"

[[columns]]
kind = "Separator"
style = "White"
numeric_search = false
nonnumeric_search = false
align = "Left"

[[columns]]
kind = "CpuTime"
style = "BrightCyan"
numeric_search = false
nonnumeric_search = false
align = "Left"

[[columns]]
kind = "Separator"
style = "White"
numeric_search = false
nonnumeric_search = false
align = "Left"

[[columns]]
kind = "Command"
style = "BrightWhite"
numeric_search = false
nonnumeric_search = true
align = "Left"

[display]
show_self = false
cut_to_terminal = true
separator = "│"
ascending = ""
descending = ""
tree_symbols = ["│", "─", "┬", "├", "└"]

[sort]
column = 2
order = "Descending"

